import type { CollectionConfig } from 'payload'
import { isAdmin, publishedOrAuthenticated } from '../access'
import {
  HeroBlock,
  SubheroBlock,
  BenefitGridBlock,
  ProcessStepsBlock,
  FaqBlock,
  PricingDetailBlock,
  InteractiveToolsBlock,
  RequirementsListBlock,
  StatsRowBlock,
  ServicesGridBlock,
  JurisdictionsGridBlock,
  TestimonialsBlock,
  GlobalCtaBlock,
  LeadMagnetsBlock,
  TickerBlock,
  PricingCardsBlock,
  ComparisonToolBlock,
  JurisdictionQuizBlock,
  LeadFormBlock,
} from '../blocks'

export const Pages: CollectionConfig = {
  slug: 'pages',
  admin: {
    useAsTitle: 'title',
    defaultColumns: ['title', 'slug', 'pageType', '_status', 'updatedAt'],
    group: 'Pages',
  },
  access: {
    create: isAdmin,
    read: publishedOrAuthenticated,
    update: isAdmin,
    delete: isAdmin,
  },
  versions: { drafts: true },
  fields: [
    { name: 'title', type: 'text', required: true, localized: true },
    {
      name: 'slug',
      type: 'text',
      required: true,
      unique: true,
      admin: { description: 'Use "home" for the homepage, otherwise use URL slugs like tax-guide or thank-you.' },
    },
    {
      name: 'pageType',
      type: 'select',
      defaultValue: 'generic',
      options: [
        { label: 'Generic Page', value: 'generic' },
        { label: 'Landing Page', value: 'landing' },
        { label: 'Campaign Page', value: 'campaign' },
        { label: 'Thank You Page', value: 'thank-you' },
      ],
    },
    {
      name: 'layout',
      type: 'blocks',
      localized: true,
      blocks: [
        HeroBlock,
        TickerBlock,
        SubheroBlock,
        BenefitGridBlock,
        ProcessStepsBlock,
        FaqBlock,
        PricingDetailBlock,
        PricingCardsBlock,
        ComparisonToolBlock,
        JurisdictionQuizBlock,
        LeadFormBlock,
        InteractiveToolsBlock,
        RequirementsListBlock,
        StatsRowBlock,
        ServicesGridBlock,
        JurisdictionsGridBlock,
        TestimonialsBlock,
        GlobalCtaBlock,
        LeadMagnetsBlock,
      ],
    },
    {
      name: 'seo',
      type: 'group',
      localized: true,
      fields: [
        { name: 'metaTitle', type: 'text' },
        { name: 'metaDescription', type: 'textarea' },
        { name: 'canonicalUrl', type: 'text' },
        { name: 'noIndex', type: 'checkbox', defaultValue: false },
      ],
    },
  ],
}
